-- The fourth system of the two-way demo, and the first one the platform may
-- not read directly (#97, ADR 0027): a loyalty scheme that exposes its
-- members over HTTP and nothing else.
--
--   psql -U postgres -f demo/integration/loyalty_setup.sql
--
-- Its records live in a database of its own, like the shop's. That database
-- is the scheme's, not ours: nothing here reads it except the scheme's own
-- API (demo/integration/loyalty_api.py), which is the whole point -- a flow
-- polls the endpoint, and the hub never sees this table.
--
-- No replication slot to drop first, for the same reason: no CDC reads it.
drop database if exists loyalty with (force);
create database loyalty;
\connect loyalty

create table member (
    member_no  bigint generated by default as identity (start with 9000) primary key,
    full_name  text      not null,
    vkn        text,
    is_active  boolean   not null default true,
    tier       text      not null default 'Standart',
    -- What the answer carries as `updated_ms`. The hub decides a conflict by
    -- commit time and an API has none of its own, so the scheme states when
    -- it last changed a member and the flow is refused without it (ADR 0027).
    updated_at timestamp not null default now()
);

-- A member's row moves whenever the scheme changes it; the API turns this
-- into epoch milliseconds, which is what a flow reads.
create function touch() returns trigger language plpgsql as $$
begin
    new.updated_at := now();
    return new;
end $$;
create trigger member_touch before update on member
    for each row execute function touch();

-- One member the other three systems already hold, found by its tax number
-- at the first sync, and one the scheme alone has, which becomes a record.
insert into member (full_name, vkn, is_active, tier) values
    ('Ege Tekstil',      '5678901234', true, 'Altın'),
    ('Toros Kimya A.Ş.', '8901234567', true, 'Standart');
