-- The third system of the two-way demo (#82, #83): an online shop, on the
-- platform's own Postgres in a database of its own. It numbers customers its
-- own way, like the other two, and keeps one city. Three customers the others
-- hold too -- one under a third spelling -- and one only it has.
--
--   psql -U postgres -f demo/integration/shop_setup.sql
--
-- A flow reading it holds a replication slot there, so the database is only
-- dropped after the slots are.
select pg_drop_replication_slot(slot_name) from pg_replication_slots
 where database = 'shop' and not active;
drop database if exists shop with (force);
create database shop;
\connect shop

create table customer (
    customer_no bigint generated by default as identity (start with 5000) primary key,
    full_name   text        not null,
    vat_number  text,
    is_active   boolean     not null default true,
    city        text,
    -- Not timestamptz: SeaTunnel 2.3.13's Postgres CDC refuses the whole table
    -- over one (core/flow_schema.py reports it before a job is submitted).
    created_at  timestamp   not null default now()
);
-- Postgres CDC carries a before image only with the whole old row (ADR 0020).
alter table customer replica identity full;

insert into customer (customer_no, full_name, vat_number, is_active, city) values
    (4001, 'Anadolu Gıda',        '1234567890', true,  'İstanbul'),
    (4002, 'Delta Ltd. Şti.',     '4567890123', true,  'Ankara'),
    (4003, 'Ege Tekstil',         '5678901234', true,  null),
    (4004, 'Gökçe Mağazacılık',   '7890123456', true,  'Bursa');
